VERSION = (0, 0)
VERSION_STRING = '.'.join(str(i) for i in VERSION)

SPAETI_ACCOUNT_USERNAME = 'spaeti'
SPAETI_DEFAULT_BANK_ACCOUNT_NAME = 'default'
SPAETI_DEFAULT_PRODUCT_CATEGORY_NAME_PLURAL = 'Drinks'
SPAETI_DEFAULT_PRODUCT_CATEGORY_NAME = 'Drink'
SPAETI_DEFAULT_PRODUCT_CATEGORY_SLUG = 'drinks'
